services:
  backend:
    build: ./backend
    container_name: abalone_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
    networks:
      - abalone_network  
        
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    container_name: abalone_frontend
    ports:
      - "80:4173"
    depends_on:
      - backend
    networks:
      - abalone_network

networks:
  abalone_network:
    driver: bridge
