services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: abalone_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/models:/app/models:ros
    networks:
      - abalone_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: abalone_frontend
    restart: unless-stopped    
    ports:
      - "3000:4173"    
    depends_on:
      - backend    
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - abalone_network

networks:
  abalone_network:
    driver: bridge

volumes:
  models_data:
    driver: local